[project]
name = "adk-pipe"
version = "0.1.0"
description = ""
authors = [
    {name = "Jordan",email = "jordantotten@google.com"}
]
readme = "README.md"
package-mode = true

requires-python = ">=3.13, <4.0"
dependencies = [
    "google-genai (>=1.19.0,<2.0.0)",
    "google-cloud-aiplatform[adk,agent-engines] (==1.119.0)",
    "google-adk (==1.15.1)",
    "pandas (>=2.3.2,<3.0.0)",
    "google-cloud-bigquery (>=3.36.0,<4.0.0)",
    "db-dtypes (>=1.4.3,<2.0.0)",
    "tabulate (>=0.9.0,<0.10.0)",
    "uvicorn (>=0.35.0,<0.36.0)",
    "fastapi (>=0.116.1,<0.117.0)",
    "pillow (>=11.3.0,<12.0.0)",
    "markdown (>=3.8.2,<4.0.0)",
    "markdown-pdf (>=1.9,<2.0)",
    "absl-py (>=2.3.1,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
